/**
* Cheflink - Self Ordering System 3.0
* Test Description
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.fabdav.cheflinkapi.apis

import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.response.*
import io.ktor.server.routing.*

fun Route.MenuApi() {
    route("/restaurants/{restaurantId}/menu") {
        get {
            val exampleContentType = "application/json"
            val exampleContentString = """{
              "menu" : [ {
                "sortNumber" : 6,
                "name" : "name",
                "id" : 0,
                "status" : "visible",
                "products" : [ {
                  "price" : 5.962134,
                  "name" : "name",
                  "discountPrice" : 5.637377,
                  "description" : "description",
                  "id" : 1,
                  "categoryId" : 2,
                  "allergens" : [ "allergens", "allergens" ]
                }, {
                  "price" : 5.962134,
                  "name" : "name",
                  "discountPrice" : 5.637377,
                  "description" : "description",
                  "id" : 1,
                  "categoryId" : 2,
                  "allergens" : [ "allergens", "allergens" ]
                } ]
              }, {
                "sortNumber" : 6,
                "name" : "name",
                "id" : 0,
                "status" : "visible",
                "products" : [ {
                  "price" : 5.962134,
                  "name" : "name",
                  "discountPrice" : 5.637377,
                  "description" : "description",
                  "id" : 1,
                  "categoryId" : 2,
                  "allergens" : [ "allergens", "allergens" ]
                }, {
                  "price" : 5.962134,
                  "name" : "name",
                  "discountPrice" : 5.637377,
                  "description" : "description",
                  "id" : 1,
                  "categoryId" : 2,
                  "allergens" : [ "allergens", "allergens" ]
                } ]
              } ]
            }"""
            
            when (exampleContentType) {
                "application/json" -> call.respond(exampleContentString)
                else -> call.respondText(exampleContentString)
            }
            
        }
    }

    route("/restaurants/{restaurantId}/menu/categories/{categoryId}/products/{productId}") {
        get {
            val exampleContentType = "application/json"
            val exampleContentString = """{
              "price" : 6.0274563,
              "variations" : [ {
                "min" : 5,
                "max" : 2,
                "sortNumber" : 7,
                "name" : "name",
                "description" : "description",
                "id" : 5,
                "modifiers" : [ {
                  "price" : 3.6160767,
                  "name" : "name",
                  "discountPrice" : 2.027123,
                  "modifierGroupName" : "modifierGroupName",
                  "id" : 9,
                  "status" : "visible",
                  "allergens" : [ "allergens", "allergens" ],
                  "modifierGroupId" : 4
                }, {
                  "price" : 3.6160767,
                  "name" : "name",
                  "discountPrice" : 2.027123,
                  "modifierGroupName" : "modifierGroupName",
                  "id" : 9,
                  "status" : "visible",
                  "allergens" : [ "allergens", "allergens" ],
                  "modifierGroupId" : 4
                } ]
              }, {
                "min" : 5,
                "max" : 2,
                "sortNumber" : 7,
                "name" : "name",
                "description" : "description",
                "id" : 5,
                "modifiers" : [ {
                  "price" : 3.6160767,
                  "name" : "name",
                  "discountPrice" : 2.027123,
                  "modifierGroupName" : "modifierGroupName",
                  "id" : 9,
                  "status" : "visible",
                  "allergens" : [ "allergens", "allergens" ],
                  "modifierGroupId" : 4
                }, {
                  "price" : 3.6160767,
                  "name" : "name",
                  "discountPrice" : 2.027123,
                  "modifierGroupName" : "modifierGroupName",
                  "id" : 9,
                  "status" : "visible",
                  "allergens" : [ "allergens", "allergens" ],
                  "modifierGroupId" : 4
                } ]
              } ],
              "name" : "name",
              "discountPrice" : 1.4658129,
              "description" : "description",
              "extras" : [ {
                "min" : 5,
                "max" : 2,
                "sortNumber" : 7,
                "name" : "name",
                "description" : "description",
                "id" : 5,
                "modifiers" : [ {
                  "price" : 3.6160767,
                  "name" : "name",
                  "discountPrice" : 2.027123,
                  "modifierGroupName" : "modifierGroupName",
                  "id" : 9,
                  "status" : "visible",
                  "allergens" : [ "allergens", "allergens" ],
                  "modifierGroupId" : 4
                }, {
                  "price" : 3.6160767,
                  "name" : "name",
                  "discountPrice" : 2.027123,
                  "modifierGroupName" : "modifierGroupName",
                  "id" : 9,
                  "status" : "visible",
                  "allergens" : [ "allergens", "allergens" ],
                  "modifierGroupId" : 4
                } ]
              }, {
                "min" : 5,
                "max" : 2,
                "sortNumber" : 7,
                "name" : "name",
                "description" : "description",
                "id" : 5,
                "modifiers" : [ {
                  "price" : 3.6160767,
                  "name" : "name",
                  "discountPrice" : 2.027123,
                  "modifierGroupName" : "modifierGroupName",
                  "id" : 9,
                  "status" : "visible",
                  "allergens" : [ "allergens", "allergens" ],
                  "modifierGroupId" : 4
                }, {
                  "price" : 3.6160767,
                  "name" : "name",
                  "discountPrice" : 2.027123,
                  "modifierGroupName" : "modifierGroupName",
                  "id" : 9,
                  "status" : "visible",
                  "allergens" : [ "allergens", "allergens" ],
                  "modifierGroupId" : 4
                } ]
              } ],
              "id" : 0,
              "allergens" : [ "allergens", "allergens" ]
            }"""
            
            when (exampleContentType) {
                "application/json" -> call.respond(exampleContentString)
                else -> call.respondText(exampleContentString)
            }
            
        }
    }

}
