/**
 * Cheflink - Self Ordering System 3.0
 * Test Description
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package dev.fabdav.cheflinkapi.apis

import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.response.*
import io.ktor.server.routing.*

fun Route.ModifierGroupApi() {
    route("/products/{productId}/modifier-groups") {
        post {
            val exampleContentType = "application/json"
            val exampleContentString = """{
              "min" : 6,
              "max" : 1,
              "sortNumber" : 5,
              "name" : "name",
              "description" : "description",
              "id" : 0,
              "modifiers" : [ {
                "price" : 2.302136,
                "sortNumber" : 9,
                "name" : "name",
                "discountPrice" : 7.0614014,
                "id" : 5,
                "status" : "visible",
                "modifierGroupId" : 3
              }, {
                "price" : 2.302136,
                "sortNumber" : 9,
                "name" : "name",
                "discountPrice" : 7.0614014,
                "id" : 5,
                "status" : "visible",
                "modifierGroupId" : 3
              } ]
            }"""

            when (exampleContentType) {
                "application/json" -> call.respond(exampleContentString)
                else -> call.respondText(exampleContentString)
            }

        }
    }

    route("/modifier-groups/{modifierGroupId}") {
        delete {
            call.respond(HttpStatusCode.NotImplemented)

        }
    }

    route("/products/{productId}/modifier-groups/{modifierGroupId}") {
        get {
            val exampleContentType = "application/json"
            val exampleContentString = """{
              "min" : 6,
              "max" : 1,
              "sortNumber" : 5,
              "name" : "name",
              "description" : "description",
              "id" : 0,
              "modifiers" : [ {
                "price" : 2.302136,
                "sortNumber" : 9,
                "name" : "name",
                "discountPrice" : 7.0614014,
                "id" : 5,
                "status" : "visible",
                "modifierGroupId" : 3
              }, {
                "price" : 2.302136,
                "sortNumber" : 9,
                "name" : "name",
                "discountPrice" : 7.0614014,
                "id" : 5,
                "status" : "visible",
                "modifierGroupId" : 3
              } ]
            }"""

            when (exampleContentType) {
                "application/json" -> call.respond(exampleContentString)
                else -> call.respondText(exampleContentString)
            }

        }
    }

    route("/products/{productId}/modifier-groups") {
        get {
            val exampleContentType = "application/json"
            val exampleContentString = """{
              "assignedModifierGroups" : [ {
                "sortNumber" : 6,
                "name" : "name",
                "id" : 0
              }, {
                "sortNumber" : 6,
                "name" : "name",
                "id" : 0
              } ],
              "availableModifierGroups" : [ {
                "sortNumber" : 6,
                "name" : "name",
                "id" : 0
              }, {
                "sortNumber" : 6,
                "name" : "name",
                "id" : 0
              } ]
            }"""

            when (exampleContentType) {
                "application/json" -> call.respond(exampleContentString)
                else -> call.respondText(exampleContentString)
            }

        }
    }

    route("/products/{productId}/modifier-groups") {
        patch {
            call.respond(HttpStatusCode.NotImplemented)

        }
    }

    route("/modifier-groups/{modifierGroupId}") {
        patch {
            val exampleContentType = "application/json"
            val exampleContentString = """{
              "min" : 6,
              "max" : 1,
              "sortNumber" : 5,
              "name" : "name",
              "description" : "description",
              "id" : 0,
              "modifiers" : [ {
                "price" : 2.302136,
                "sortNumber" : 9,
                "name" : "name",
                "discountPrice" : 7.0614014,
                "id" : 5,
                "status" : "visible",
                "modifierGroupId" : 3
              }, {
                "price" : 2.302136,
                "sortNumber" : 9,
                "name" : "name",
                "discountPrice" : 7.0614014,
                "id" : 5,
                "status" : "visible",
                "modifierGroupId" : 3
              } ]
            }"""

            when (exampleContentType) {
                "application/json" -> call.respond(exampleContentString)
                else -> call.respondText(exampleContentString)
            }

        }
    }

}
