/**
* Cheflink - Self Ordering System 3.0
* Test Description
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.fabdav.cheflinkapi.apis

import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.response.*
import io.ktor.server.routing.*

fun Route.RestaurantApi() {

    route("/restaurants/{restaurantId}") {
        get {
            val exampleContentType = "application/json"
            val exampleContentString = """{
              "name" : "name",
              "bannerUrl" : "bannerUrl",
              "id" : "id"
            }"""
            
            when (exampleContentType) {
                "application/json" -> call.respond(exampleContentString)
                else -> call.respondText(exampleContentString)
            }
            
        }
    }

}
